groups:
- name: node_alerts
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 10
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected on node {{ $labels.instance }}"
      description: "CPU usage is above 10% for more than 1 minutes."

