alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: 'default'
    receivers:
      - name: 'default'
        email_configs:
          - to: 'imakhilthyadi@gmail.com'  # your email here
            send_resolved: true

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelector:
      matchLabels:
        role: alert-rules

nodeExporter:
  enabled: true

